# Generated by Django 3.1.7 on 2021-03-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, choices=[('한펠', '한펠'), ('허니텍', '허니텍'), ('(주)허니텍', '(주)허니텍'), ('대한산업', '대한산업'), ('기타', '기타')], max_length=10, null=True),
        ),
    ]
