# Generated by Django 3.1.7 on 2021-03-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, choices=[('(주)한펠', '(주)한펠'), ('허니텍', '허니텍'), ('(주)허니텍', '(주)허니텍'), ('대한산업', '대한산업'), ('기타', '기타')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='working_place',
            field=models.CharField(blank=True, choices=[('안양', '안양'), ('발산리 구공장', '발산리 구공장'), ('발산리 신공장', '발산리 신공장'), ('장산리', '장산리')], max_length=10, null=True),
        ),
    ]
