# Generated by Django 3.1.7 on 2021-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('attachment1', models.ImageField(blank=True, upload_to='images')),
                ('attachment2', models.FileField(blank=True, upload_to='files')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
