# Generated by Django 3.1.7 on 2021-04-06 05:05

from django.db import migrations, models
import django.db.models.deletion
import issues.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='IssueFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('첨부파일', models.FileField(blank=True, upload_to='files/', validators=[issues.validators.validate_file_size])),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issue')),
            ],
        ),
    ]
