# Generated by Django 3.1.7 on 2021-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuefile',
            name='file',
        ),
        migrations.AddField(
            model_name='issuefile',
            name='첨부파일',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
