# Generated by Django 3.1.7 on 2021-04-06 03:18

from django.db import migrations, models
import issues.validators


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20210328_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuefile',
            name='첨부파일',
            field=models.FileField(blank=True, upload_to='files/', validators=[issues.validators.validate_file_size]),
        ),
    ]
